[workspace]
members = [
  "gossip-lib",
  "gossip-bin",
]
resolver = "2"

# Force scrypt to build with release-like speed even in dev mode
[profile.dev.package.scrypt]
opt-level = 3
debug-assertions = false
overflow-checks = false

[patch.crates-io]
# override egui crate for egui_video dependency
egui = { git =  "https://github.com/mikedilger/egui", rev = "50393e4f34ac6246b8c2424e42fbe5b95e4b4452" }
# Use the master branch of SDL2 to include a fix related to clang (and XCode after 14.2)
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", rev = "f2f1e29a416bcc22f2faf411866db2c8d9536308" }

# Patch zbus since it had a dependency options bug that isn't live yet
zbus = { git = "https://github.com/dbus2/zbus/", branch = "zbus-3" }
zbus_names = { git = "https://github.com/dbus2/zbus/", branch = "zbus-3" }
