[package]
name = "gossip-lib"
version = "0.9.0-unstable"
description = "A social media client for nostr"
authors = ["Mike Dilger <mike@mikedilger.com>", "fiatjaf <fiatjaf@gmail.com>", "Nate Levin <natelevincycling@gmail.com>", "Nethanja Focking <nethanja@nethanja.de>", "Daniele Tonon <tonon@vitamino.it>", "jeremyd (@jeremyd)"]
license = "MIT"
repository = "https://github.com/mikedilger/gossip"
homepage = "https://github.com/mikedilger/gossip"
edition = "2021"

[features]
default = ["rustls-tls"]
lang-cjk = []

native-tls = [ "reqwest/native-tls", "tungstenite/native-tls", "tokio-tungstenite/native-tls"]
rustls-tls = [ "reqwest/rustls-tls", "tungstenite/rustls-tls-webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots"]

[dependencies]
async-recursion = "1.0"
async-trait = "0.1"
base64 = "0.21"
bech32 = "0.9"
dashmap = "5.4"
dirs = "5.0"
encoding_rs = "0.8"
fallible-iterator = "0.2"
filetime = "0.2"
futures = "0.3"
futures-util = "0.3"
gossip-relay-picker = { git = "https://github.com/mikedilger/gossip-relay-picker", rev = "39f9c14b1c201842c512754920f4da4987cd68b6" }
heed = { git = "https://github.com/meilisearch/heed", rev = "02030e3bf3d26ee98d4f5343fc086a7b63289159" }
hex = "0.4"
http = "0.2"
image = { version = "0.24.6", features = [ "png", "jpeg" ] }
kamadak-exif = "0.5"
lazy_static = "1.4"
linkify = "0.9"
mime = "0.3"
nostr-types = { git = "https://github.com/mikedilger/nostr-types", rev = "61ed6d8ab07363ee5861e7460e795b32b131460a", features = [ "speedy" ] }
parking_lot = "0.12"
paste = "1.0"
rand = "0.8"
regex = "1.8"
reqwest = { version = "0.11", default-features=false, features = ["brotli", "deflate", "gzip", "json"] }
resvg = "0.35.0"
rhai = { version = "1.15", features = [ "std", "sync" ]}
rusqlite = { version = "0.29", features = ["bundled", "chrono", "serde_json"] }
sdl2 = { version = "0.35.2", features = ["bundled"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
speedy = { git = "https://github.com/mikedilger/speedy", rev = "b8b713a7006958616dd3ef3ba63217740b4b09c2" }
tiny-skia = "0.10.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tokio-tungstenite = { version = "0.19", default-features = false, features = [ "connect", "handshake" ] }
tungstenite = { version = "0.19", default-features = false }
url = "2.4"
usvg = "0.35.0"
zeroize = "1.6"

[target.'cfg(windows)'.dependencies]
normpath = "1.1"
